# Generated by Django 3.1.1 on 2020-09-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200914_0818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='CompanyDetail',
        ),
    ]
