# Generated by Django 3.1.1 on 2020-09-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200914_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company'),
        ),
    ]
