# Generated by Django 3.1.1 on 2020-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True, default='1000-10-10 10:10'),
            preserve_default=False,
        ),
    ]
