# Generated by Django 3.1.1 on 2020-09-15 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200915_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='time_sent',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
