# Generated by Django 3.1.1 on 2020-09-16 09:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200915_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('hero_title', models.CharField(max_length=100)),
                ('hero_subtitle', models.CharField(max_length=250)),
                ('intro_title', models.CharField(max_length=100)),
                ('intro_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('logos_title', models.CharField(max_length=100)),
                ('team_title', models.CharField(max_length=100)),
                ('contact_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
            },
        ),
    ]
