# Generated by Django 3.1.1 on 2020-09-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
        migrations.RenameField(
            model_name='home',
            old_name='description',
            new_name='meta_description',
        ),
    ]
