# Generated by Django 3.1.1 on 2020-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200916_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='team_link_text',
            field=models.CharField(default='See entire team', max_length=100),
            preserve_default=False,
        ),
    ]
