# Generated by Django 3.1.1 on 2020-09-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disclaimer',
            old_name='subtitle',
            new_name='hero_subtitle',
        ),
        migrations.RenameField(
            model_name='privacypolicy',
            old_name='subtitle',
            new_name='hero_subtitle',
        ),
        migrations.RenameField(
            model_name='termsofservice',
            old_name='subtitle',
            new_name='hero_subtitle',
        ),
        migrations.AddField(
            model_name='disclaimer',
            name='hero_title',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disclaimer',
            name='meta_description',
            field=models.CharField(default='blank', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hero_title',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='meta_description',
            field=models.CharField(default='blank', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='hero_title',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='meta_description',
            field=models.CharField(default='blank', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
